[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  command   = "pnpm run build"
  publish   = "public"
  functions = "netlify/functions"

[[redirects]]
  from      = "/*"
  to        = "/.netlify/functions/remix"
  status    = 200
